<?php

namespace Echidna\Yves\GoogleAnalytics\Twig;

use Codeception\Test\Unit;
use Echidna\Yves\GoogleAnalytics\Dependency\Client\GoogleAnalyticsToCartClientInterface;
use Echidna\Yves\GoogleAnalytics\Dependency\Client\GoogleAnalyticsToSessionClientInterface;
use Echidna\Yves\GoogleAnalytics\Model\DataLayer\DefaultVariableBuilder;
use Echidna\Yves\GoogleAnalytics\Model\DataLayer\ProductVariableBuilder;
use Twig_Environment;

class GoogleAnalyticsTwigExtensionTest extends Unit
{
    /**
     * @var \Echidna\Yves\GoogleAnalytics\Dependency\Client\GoogleAnalyticsToCartClientInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $GoogleAnalyticsToCartClientMock;

    /**
     * @var \Echidna\Yves\GoogleAnalytics\Dependency\Client\GoogleAnalyticsToSessionClientInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $GoogleAnalyticsToSessionClientMock;

    /**
     * @var \Echidna\Yves\GoogleAnalytics\Dependency\Client\GoogleAnalyticsToSessionClientInterface|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $variableBuildersCollectionMock;

    /**
     * @var \Echidna\Yves\GoogleAnalytics\Model\DataLayer\DefaultVariableBuilder|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $defaultVariableBuilderMock;

    /**
     * @var \Echidna\Yves\GoogleAnalytics\Model\DataLayer\ProductVariableBuilder|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $productDetailVariableBuilderMock;

    /**
     * @var \Twig_Environment|\PHPUnit\Framework\MockObject\MockObject
     */
    protected $twigEnvironmentMock;

    /**
     * @return void
     */
    protected function _before()
    {
        parent::_before(); // TODO: Change the autogenerated stub

        $this->GoogleAnalyticsToCartClientMock = $this->getMockBuilder(GoogleAnalyticsToCartClientInterface::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->GoogleAnalyticsToSessionClientMock = $this->getMockBuilder(GoogleAnalyticsToSessionClientInterface::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->twigEnvironmentMock = $this->getMockBuilder(Twig_Environment::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->productDetailVariableBuilderMock = $this->getMockBuilder(ProductVariableBuilder::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->defaultVariableBuilderMock = $this->getMockBuilder(DefaultVariableBuilder::class)
            ->disableOriginalConstructor()
            ->getMock();
    }
}
